name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ver entorno
        run: echo "entorno actual ${{ secrets.NODE_ENV }}"

      - name: clonar repositorio
        uses: actions/checkout@v3
  
      - name: usar node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
  
      - name: instalar dependencias
        run: npm install
  
      - name: ejecutar pruebas
        run: npm test
